### ISSUE TITLE
Not compiling in Arduino IDE 1.8.13

### ISSUE THREAD

**Issue by VikingVoltage** [VasilKalchev/ExponentMap#4]
I'm a newbie. Wondering if I've got issues I need to work out, or if somethings changed w the Arduino IDE etc. I can not get the code to compile, regardless of board selected. 

I'm probably doing something wrong. Please let me know if it compiles for you.

**Comment by VasilKalchev** [comment]
Hello VikingVoltage, sorry for the delay.

I think the problem was from a newer version of the compiler. It is fixed now, thanks for reporting it.
